version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      day: "friday"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      day: "friday"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "rails"
      - dependency-name: "sass-rails"
      - dependency-name: "haml-rails"
      - dependency-name: "slack-notifier"
      - dependency-name: "pg"
      - dependency-name: "sprockets-rails"
