devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

omniauth:
  github:
    client_id: <%= ENV['OMNIAUTH_GITHUB_CLIENT_ID'] || '' %>
    client_secret: <%= ENV['OMNIAUTH_GITHUB_CLIENT_SECRET'] || '' %>
    organization: <%= ENV['OMNIAUTH_GITHUB_ORGANIZATION'] || '' %>

