name: CI Docker

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-app:
    uses: ./.github/workflows/_ci-docker.yml

  ci-lambda:
    uses: ./.github/workflows/_ci-docker.yml
    with:
      target: lambda
