name: Push Docker Image to GHCR

on:
  push:
    branches: [ "master" ]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ghcr-app:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_ghcr.yml
    with:
      image_name: ghcr.io/${{ github.repository_owner }}/sunline

  ghcr-lambda:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_ghcr.yml
    with:
      image_name: ghcr.io/${{ github.repository_owner }}/sunline-lambda
      target: lambda
