name: Push Docker Image to GHCR

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ghcr-app:
    uses: ./.github/workflows/_ghcr.yml
    with:
      image_name: ghcr.io/${{ github.repository_owner }}/sunline

  ghcr-lambda:
    uses: ./.github/workflows/_ghcr.yml
    with:
      image_name: ghcr.io/${{ github.repository_owner }}/sunline-lambda
      dockerfile: Dockerfile.lambda
